name = "Create-Delight-Remake"
author = "JSI"
version = "v0.4.8.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14d6d78b0931413c7c252c72e8f939d88210b965bf25182cff7181776c3e2867"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
