name = "Create-Delight-Remake"
author = "JSI"
version = "v0.4.8.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6fb8d92ec8728ce954b6a1eab8c3770692c4a8346525038d96bf38b67e13479b"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
