VersionOriginalSub:1
State:6
VersionAdvanceJvm:-Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError
VersionVanillaName:1.20.1
VersionArgumentIndieV2:True
VersionVanilla:20.0.1
Info:正式版 1.20.1, Forge 47.4.16
LogoCustom:True
VersionOriginal:1.20.1
VersionLiteLoader:False
Logo:PCL\Logo.png
ReleaseTime:2026-01-21 05:34
VersionApiCode:47040016
VersionForge:47.4.16
VersionOriginalMain:20
