// 默认食材价值，如果希望是其他值，加入Dict
const DefaultFoodIngredientValue = 1;
// 默认价值列表
// 如果是食材，建议考虑统一添加#quality_food:material_whitelist标签，而不是加入这个列表
let DefaultFoodIngredientList = [
    "#quality_food:material_whitelist",

    "minecraft:sunflower",

    "alexscaves:pine_nuts",
    "alexscaves:trilocaris_tail",
    "alexscaves:tree_star",

    "crabbersdelight:clawster",
    "crabbersdelight:raw_frog_leg",
    "crabbersdelight:shrimp",

    "farmersdelight:pie_crust",

    "festival_delicacies:greenonion",
    "festival_delicacies:eggplant",
    "festival_delicacies:garlic_chive",

    "vintagedelight:ghost_pepper",
    "vintagedelight:gearo_berry",
    "vintagedelight:oats",
    "vintagedelight:salt_dust",

    "neapolitan:banana",
    "neapolitan:mint_leaves",
    "neapolitan:vanilla_pods",
    "neapolitan:strawberries",

    "mynethersdelight:bullet_pepper",
    "mynethersdelight:powder_cannon",
    "mynethersdelight:ghasmati",

    "youkaishomecoming:mandrake_flower",
    "youkaishomecoming:raw_lamprey",

    "nethervinery:crimson_grape",
    "nethervinery:warped_grape",

    "vinery:cherry",
    "vinery:red_grape",
    "vinery:white_grape",
    "vinery:savanna_grapes_red",
    "vinery:savanna_grapes_white",
    "vinery:taiga_grapes_red",
    "vinery:taiga_grapes_white",
    "vinery:jungle_grapes_red",
    "vinery:jungle_grapes_white",

    "fruitsdelight:pear",
    "fruitsdelight:hawberry",
    "fruitsdelight:lychee",
    "fruitsdelight:mango",
    "fruitsdelight:persimmon",
    "fruitsdelight:peach",
    "fruitsdelight:orange",
    "fruitsdelight:mangosteen",
    "fruitsdelight:bayberry",
    "fruitsdelight:kiwi",
    "fruitsdelight:fig",
    "fruitsdelight:blueberry",
    "fruitsdelight:lemon",
    "fruitsdelight:cranberry",
    "fruitsdelight:pineapple",
    "fruitsdelight:durian",

    "oceanic_delight:sea_grape",

    "farmersrespite:green_tea_leaves",
    "farmersrespite:yellow_tea_leaves",
    "farmersrespite:black_tea_leaves",

    "collectorsreap:lime",

    "butchercraft:leather_scrap",
    "butchercraft:sinew",
    "butchercraft:fat",

    "createdelight:dry_yeast",
]

let MaterialWhitelistValueDict = {
    "minecraft:sugar": 2,
    "minecraft:sugar_cane": 1,
    "minecraft:cocoa_beans": 1,
    "minecraft:ink_sac": 1,
    "minecraft:hay_block": 9,
    "minecraft:honey_block": 8,
    "mynethersdelight:strider_egg": 4,
    "minecraft:egg": 2,
    "alexsmobs:crocodile_egg": 2,
    "alexsmobs:platypus_egg": 2,
    "alexsmobs:terrapin_egg": 2,
    "alexsmobs:caiman_egg": 2,
    "iceandfire:hippogryph_egg": 6,
    "iceandfire:deathworm_egg": 6,
    "iceandfire:myrmex_desert_egg": 6,
    "iceandfire:myrmex_jungle_egg": 6,
    "minecraft:turtle_egg": 2,
    "alexscaves:subterranodon_egg": 2,
    "alexscaves:vallumraptor_egg": 2,
    "alexscaves:grottoceratops_egg": 2,
    "quark:egg_parrot_gray": 2,
    "quark:egg_parrot_yellow_blue": 2,
    "quark:egg_parrot_green": 2,
    "quark:egg_parrot_blue": 2,
    "quark:egg_parrot_red_blue": 2,
    "endertrigon:baby_dragon_egg": 8,
    "youkaishomecoming:soybean": 1,
    "youkaishomecoming:redbean": 1,
    "youkaishomecoming:tea_seeds": 1,
    "youkaishomecoming:udumbara_seeds": 1,
    "youkaishomecoming:mandrake_root": 4,
    "youkaishomecoming:cucumber_seeds": 1,
    "youkaishomecoming:red_grape_seeds": 1,
    "youkaishomecoming:black_grape_seeds": 1,
    "youkaishomecoming:white_grape_seeds": 1,
    "createcafe:cassava_seeds": 1,
    "createcafe:coffee_beans": 1,
    "minecraft:beetroot_seeds": 1,
    "minecraft:melon_seeds": 1,
    "minecraft:pumpkin_seeds": 1,
    "minecraft:wheat_seeds": 1,
    "frycooks_delight:canola_seeds": 1,
    "farmersdelight:cabbage_seeds": 1,
    "farmersdelight:rice": 1,
    "farmersdelight:tomato_seeds": 1,
    "corn_delight:corn_seeds": 1,
    "culturaldelights:cucumber_seeds": 1,
    "culturaldelights:eggplant_seeds": 1,
    "culturaldelights:corn_kernels": 1,
    "culturaldelights:avocado_pit": 1,
    "vinery:red_grape_seeds": 1,
    "vinery:white_grape_seeds": 1,
    "vinery:savanna_grape_seeds_red": 1,
    "vinery:savanna_grape_seeds_white": 1,
    "vinery:taiga_grape_seeds_red": 1,
    "vinery:taiga_grape_seeds_white": 1,
    "vinery:jungle_grape_seeds_red": 1,
    "vinery:jungle_grape_seeds_white": 1,
    "create_bic_bit:sunflower_seeds": 1,
    "neapolitan:strawberry_pips": 1,
    "collectorsreap:lime_seeds": 1,
    "collectorsreap:pomegranate_seeds": 1,
    "collectorsreap:dragon_fruit_seeds": 1,
    "collectorsreap:damselflower_seeds": 1,
    "collectorsreap:moontear_seeds": 1,
    "collectorsreap:skull_lily_seeds": 1,
    "collectorsreap:bulbous_rose_seeds": 1,
    "collectorsreap:heartpetals_seeds": 1,
    "supplementaries:flax_seeds": 1,
    "cosmopolitan:source_berry_pips": 1,
    "cosmopolitan:kabloom_pips": 1,
    "cosmopolitan:blisterberry_pips": 1,
    "cosmopolitan:droopfruit_pips": 1,
    "createdelight:adzuki_beans_seed": 1,
    "createdelight:artemisia_argyi_seed": 1,
    "festival_delicacies:chinese_cabbage_seeds": 1,
    "festival_delicacies:eggplant_seeds": 1,
    "festival_delicacies:garlic_chive_seeds": 1,
    "festival_delicacies:fennel_seeds": 1,
    "festival_delicacies:garlic": 1,
    "vintagedelight:oat_seeds": 1,
    "vintagedelight:peanut": 1,
    "vintagedelight:cucumber_seeds": 1,
    "vintagedelight:ghost_pepper_seeds": 1,
    "createcafe:cassava_root": 1,
    "createcafe:coffee_fruit": 1,
    "miners_delight:cave_carrot": 1,
    "minecraft:beetroot": 1,
    "minecraft:carrot": 1,
    "minecraft:nether_wart": 1,
    "minecraft:potato": 1,
    "cosmopolitan:cut_potatoes": 1,
    "minecraft:wheat": 1,
    "frycooks_delight:canola": 1,
    "farmersdelight:cabbage": 1,
    "farmersdelight:cabbage_leaf": 1,
    "festival_delicacies:chinese_cabbage": 2,
    "festival_delicacies:chinese_cabbage_leaf": 1,
    "farmersdelight:onion": 1,
    "festival_delicacies:rice": 1,
    "mynethersdelight:ghasmati": 1,
    "farmersdelight:tomato": 1,
    "culturaldelights:cucumber": 1,
    "culturaldelights:cut_cucumber": 1,
    "culturaldelights:eggplant": 1,
    "culturaldelights:cut_eggplant": 1,
    "culturaldelights:white_eggplant": 1,
    "culturaldelights:corn_cob": 1,
    "culturaldelights:avocado": 1,
    "culturaldelights:cut_avocado": 1,
    "supplementaries:flax": 1,
    "cosmopolitan:wheatgrass": 1,
    "vintagedelight:cucumber": 1,
    "minecraft:brown_mushroom": 1,
    "minecraft:red_mushroom": 1,
    "collectorsreap:portobello": 1,
    "bakeries:sweet_dough": 4,
    "mynethersdelight:ghast_dough": 4,
    "vintagedelight:oat_dough": 3,
    "farmersdelight:wheat_dough": 3,
    "bakeries:flour": 2,
    "create:wheat_flour": 2,
    "farmersdelight:rice_panicle": 2,
    "collectorsreap:pomegranate": 2,
    "farmersdelight:brown_mushroom_colony": 3,
    "farmersrespite:coffee_beans": 1,
    "farmersdelight:red_mushroom_colony": 3,
    "mynethersdelight:crimson_fungus_colony": 3,
    "mynethersdelight:warped_fungus_colony": 3,
    "collectorsreap:portobello_colony": 3,
    "minecraft:crimson_fungus": 1,
    "minecraft:warped_fungus": 1,
    "minecraft:kelp": 1,
    "create:cinder_flour": 2,
    "ratatouille:salty_dough": 3,
    "ratatouille:wheat_kernels": 1,
    "ratatouille:cocoa_solids": 2,
    "createdelight:corn_flour": 2,
    "bakeries:foamed_cream": 3,
    "createdelight:board_noodles": 2,
    "createdelight:wafer_dough": 5,
    "createdelight:vermicelli": 2,
    "createdelight:raw_cheese_pizza": 8,
    "bakeries:whole_wheat_dough": 3,
    "bakeries:bagel_dough": 4,
    "bakeries:whole_wheat_bagel_dough": 4,
    "bakeries:round_bread_dough": 4,
    "bakeries:berry_bread_dough": 5,
    "bakeries:brown_sugar_roll_dough": 6,
    "bakeries:pineapple_bun_dough": 6,
    "bakeries:croissant_dough": 5,
    "bakeries:salt_croissant_dough": 6,
    "bakeries:mould_toast_dough": 12,
    "bakeries:mould_cheese_cocoa_toast_dough": 18,
    "bakeries:baguette_dough": 4,
    "bakeries:ciabatta_dough": 4,
    "bakeries:focaccia_dough": 6,
    "bakeries:country_bread_dough": 5,
    "ratatouille:cocoa_powder": 2,
    "ratatouille:cocoa_butter": 2,
    "ratatouille:dried_cocoa_beans": 1,
    "ratatouille:dried_cocoa_nibs": 1,
    "create_bic_bit:sweet_dough": 4,
    "create_bic_bit:crushed_nether_wart": 2,
    "casualness_delight:raw_gluten": 2,
    "casualness_delight:gluten": 3,
    "casualness_delight:raw_chicken_bobo_chicken": 6,
    "casualness_delight:raw_cabbage_bobo_chicken": 5,
    "casualness_delight:raw_potato_bobo_chicken": 5,
    "casualness_delight:potato_slice": 1,
    "createcafe:oreo_dough": 4,
    "createcafe:tapioca_flour": 2,
    "dungeonsdelight:gunk": 2,
    "dungeonsdelight:rotbulb": 2,
    "dungeonsdelight:sculk_polyp": 2,
    "dungeonsdelight:spider_extract": 4,
    "dungeonsdelight:rancid_reduction": 8,
    "dungeonsdelight:ghastly_spirits": 8,
    "dungeonsdelight:bloody_mary": 6,
    "dungeonsdelight:taro_milk_tea": 12,
    "dungeonsdelight:ancient_egg": 8,
    "dungeonsdelight:sculk_mayo_block": 16,
    "dungeonsdelight:spider_pie": 10,
    "dungeonsdelight:sculk_tart": 24,
    "dungeonsdelight:monster_cake": 16,
    "dungeonsdelight:glow_berry_gelatin_block": 12,
    "dungeonsdelight:guardian_angel_block": 20,
    "ends_delight:ender_pearl_grain": 2,
    "ends_delight:dried_chorus_flower": 2,
    "ends_delight:non_hatchable_dragon_egg": 24,
    "ends_delight:dragon_breath_soda": 8,
    "ends_delight:chorus_fruit_wine": 6,
    "festival_delicacies:uncooked_sweet_zongzi": 4,
    "festival_delicacies:uncooked_meat_zongzi": 6,
    "festival_delicacies:bamboo_leaf": 1,
    "festival_delicacies:mugwort": 2,
    "cavedelight:fiddlehead_tea": 4,
    "trailandtales_delight:cherry_petal": 1,
    "trailandtales_delight:dried_cherry_petal": 2,
    "trailandtales_delight:pitcher_plant": 1,
    "farmersrespite:rose_hips": 1,
    "neapolitan:banana_bunch": 2,
    "vintagedelight:oat": 1,
    "crabbersdelight:clam": 2,
    "youkaishomecoming:pods": 2,
    "youkaishomecoming:udumbara_flower": 9,
    "youkaishomecoming:matcha": 2,
    "youkaishomecoming:stripped_mandrake_root": 5,
    "youkaishomecoming:dried_mandrake_flower": 6,
    "collectorsreap:lime_popsicle": 6,
    "collectorsreap:urchin": 4,
    "brewinandchewin:unripe_scarlet_cheese_wheel": 32,
}

let FoodIngredientValueDict = {
    // 其他价值的食材（非白名单）
    "minecraft:beef": 2,
    "minecraft:cod": 2,
    "minecraft:salmon": 2,
    "minecraft:tropical_fish": 2,
    "minecraft:chicken": 4,
    "minecraft:mutton": 4,
    "minecraft:rabbit": 4,

    "culturaldelights:squid": 2,

    "brewinandchewin:flaxen_cheese_wheel": 64,

    "mynethersdelight:hoglin_loin": 5,

    "collectorsreap:stygian_pomegranate": 2,
    "collectorsreap:tiger_prawn": 4,
    "collectorsreap:platinum_bass": 4,
    "collectorsreap:clam": 4,
    "collectorsreap:chieftain_crab_bucket": 4,

    "alexsdelight:raw_bison": 4,
    "alexsdelight:raw_bunfungus": 4,

    "alexsmobs:kangaroo_meat": 2,
    "alexsmobs:moose_ribs": 2,
    "alexsmobs:emu_egg": 2,
    "alexsmobs:raw_catfish": 2,

    "alexscaves:candy_cane": 10,

    "butchercraft:tripe": 2,
    "butchercraft:stomach": 2,
    "butchercraft:lung": 2,
    "butchercraft:liver": 2,
    "butchercraft:kidney": 2,
    "butchercraft:heart": 2,
    "butchercraft:brain": 2,

    "crabbersdelight:crab": 4,

    "createdelight:butter": 2,

    "miners_delight:wild_cave_carrots": 4,
}

// 价值黑名单，加入黑名单的物品在计算价值时会被忽略
// 不能把这些物品基础价值置为0，因为0价值物品会让他们作为输入物品参与的配方能够计算产物价值
let ValueBlackList = [
    "fruitsdelight:durian_shell",
    "fruitsdelight:durian_helmet",
]

// 保证默认价值的物品在Map中先出现，这样特殊价值的设定就可以覆盖默认价值设定
global.FoodIngredientValueDict = new Map(
    DefaultFoodIngredientList.map(item => [item, DefaultFoodIngredientValue])
        .concat(Object.entries(MaterialWhitelistValueDict))
        .concat(Object.entries(FoodIngredientValueDict))
);

global.ValueBlackList = ValueBlackList;

// 默认配方价值倍率，如果希望是其他值，加入Dict。如果值过大可能会上溢导致kjs加载失败。
global.DefaultRecipeValueMultiplier = 2;
let RecipeValueMultiplierDict = {
    "crafting": 1
}
global.RecipeValueMultiplierDict = new Map(Object.entries(RecipeValueMultiplierDict));
