LootJS.modifiers(e => {
    e.addEntityLootModifier("alexscaves:forsaken")
    .addLoot("createdelight:devil_eye")
    e.addEntityLootModifier("alexscaves:licowitch")
    .removeLoot('alexscaves:vanilla_ice_cream_scoop')
    .removeLoot('alexscaves:chocolate_ice_cream_scoop')
    .removeLoot('alexscaves:sweetberry_ice_cream_scoop')
    .addWeightedLoot([0, 1], [Item.of('createdelightcore:strawberry_ice_cream_scoop').withChance(0.33)])
    .addWeightedLoot([0, 1], [Item.of('createdelightcore:banana_ice_cream_scoop').withChance(0.33)])
    .addWeightedLoot([0, 1], [Item.of('createdelightcore:mint_ice_cream_scoop').withChance(0.33)])
    .addWeightedLoot([0, 1], [Item.of('createdelightcore:adzuki_ice_cream_scoop').withChance(0.33)])
    .addWeightedLoot([0, 1], [Item.of('createdelightcore:pomegranate_ice_cream_scoop').withChance(0.33)])
    .addWeightedLoot([0, 1], [Item.of('createdelightcore:lime_ice_cream_scoop').withChance(0.33)])
    .addWeightedLoot([0, 1], [Item.of('alexscaves:vanilla_ice_cream_scoop').withChance(0.33)])
    .addWeightedLoot([0, 1], [Item.of('alexscaves:chocolate_ice_cream_scoop').withChance(0.33)])
    .addWeightedLoot([0, 1], [Item.of('alexscaves:sweetberry_ice_cream_scoop').withChance(0.33)])
})