new Schema("createdieselgenerators:basin_fermenting")
    .simpleKey("results", "outputFluidOrItemArray")
    .simpleKey("ingredients", "inputFluidOrItemArray")
    .simpleKey("processingTime", "doubleNumber", 100)
    .simpleKey("heatRequirement", "nonEmptyString", "heated" || "superheated")

new Schema("createdieselgenerators:bulk_fermenting")
    .simpleKey("results", "outputFluidOrItemArray")
    .simpleKey("ingredients", "inputFluidOrItemArray")
    .simpleKey("processingTime", "doubleNumber", 100)
    .simpleKey("heatRequirement", "nonEmptyString", "heated" || "superheated")

new Schema("createdieselgenerators:distillation")
    .simpleKey("results", "outputFluidOrItemArray")
    .simpleKey("ingredients", "inputFluidOrItemArray")
    .simpleKey("processingTime", "doubleNumber", 100)
    .simpleKey("heatRequirement", "nonEmptyString", "heated" || "superheated")
