new Schema("ratatouille:threshing")
    .simpleKey("results", "outputItemArray")
    .simpleKey("ingredients", "inputItemArray")
    .simpleKey("processingTime", "doubleNumber", 200)
new Schema("ratatouille:squeezing")
    .simpleKey("results", "outputFluidOrItemArray")
    .simpleKey("ingredients", "inputFluidOrItemArray")
new Schema("ratatouille:freezing")
    .simpleKey("results", "outputFluidOrItemArray")
    .simpleKey("ingredients", "inputFluidOrItemArray")
new Schema("ratatouille:demolding")
    .simpleKey("results", "outputFluidOrItemArray")
    .simpleKey("ingredients", "inputFluidOrItemArray")
new Schema("ratatouille:baking")
    .simpleKey("results", "outputFluidOrItemArray")
    .simpleKey("ingredients", "inputFluidOrItemArray")
    .simpleKey("processingTime", "doubleNumber", 200)