new Schema("vintagedelight:fermenting")
    .simpleKey("output", "outputItemArray")
    .simpleKey("ingredients", "inputItemArray")
    .simpleKey("processingTime", "doubleNumber", 5000)
    .simpleKey("container", "inputItem", "")