new Schema("youkaishomecoming:drying_rack")
    .simpleKey("result", "nonEmptyString")
    .simpleKey("ingredient", "inputItem")
    .simpleKey("cookingtime", "intNumber", 200)
    .simpleKey("experience", "doubleNumber", 0.0)
    .simpleKey("category", "anyString", "misc")
// 蒸笼同样使用 SimpleCookingSerializer：result 为物品 ID 字符串，cookingtime 为整数。
new Schema("youkaishomecoming:steaming")
    .simpleKey("result", "nonEmptyString")
    .simpleKey("ingredient", "inputItem")
    .simpleKey("cookingtime", "intNumber", 100)
    .simpleKey("experience", "doubleNumber", 0.0)
    .simpleKey("category", "anyString", "misc")
new Schema("youkaishomecoming:simple_fermentation")
    .simpleKey("ingredients", "inputItemArray")
    // 原生固体发酵以 minecraft:empty、amount: 0 表示不消耗或产出流体。
    .dynamicKey(components => components.get("inputFluid")().key("inputFluid").allowEmpty())
    .dynamicKey(components => components.get("outputFluid")().key("outputFluid").allowEmpty())
    .simpleKey("results", "outputItemArray")
    .simpleKey("time", "intNumber", 1800)
new Schema("youkaishomecoming:cuisine_mixed")
    .simpleKey("result", "outputItem")
    .simpleKey("base", "nonBlankString")
    .simpleKey("first", "inputItemArray")
    .simpleKey("second", "inputItemArray")
new Schema("youkaishomecoming:cuisine_ordered")
    .simpleKey("result", "outputItem")
    .simpleKey("base", "nonBlankString")
    .simpleKey("input", "inputItemArray")
