new Schema("youkaishomecoming:drying_rack")
    .simpleKey("result", "nonEmptyString")
    .simpleKey("ingredient", "inputItem")
    .simpleKey("cookingtime", "intNumber", 200)
    .simpleKey("experience", "doubleNumber", 0.0)
    .simpleKey("category", "anyString", "misc")
new Schema("youkaishomecoming:simple_fermentation")
    .simpleKey("ingredients", "inputItemArray")
    .simpleKey("inputFluid", "inputFluid")
    .simpleKey("outputFluid", "outputFluid")
    .simpleKey("results", "outputItemArray")
    .simpleKey("time", "intNumber", 1800)
new Schema("youkaishomecoming:cuisine_mixed")
    .simpleKey("result", "outputItem")
    .simpleKey("base", "nonBlankString")
    .simpleKey("first", "inputItemArray")
    .simpleKey("second", "inputItemArray")
new Schema("youkaishomecoming:cuisine_ordered")
    .simpleKey("result", "outputItem")
    .simpleKey("base", "nonBlankString")
    .simpleKey("input", "inputItemArray")