ServerEvents.recipes(e => {
    remove_recipes_id(e, [
        "hotdog_delight:codcook_1",
        "hotdog_delight:salcook_1",
        "hotdog_delight:porkcook",
        "hotdog_delight:codrecp_2",
    ])
    e.recipes.create.mixing(
        "hotdog_delight:cod_sausage",
        [
            "ratatouille:sausage_casing",
            '#forge:raw_fishes/cod',
            "#forge:salt"
        ]
    ).id("hotdog_delight:codsrecp")
    e.recipes.create.mixing(
        "hotdog_delight:salmon_sausage",
        [
            "ratatouille:sausage_casing",
            '#forge:raw_fishes/salmon',
            "#forge:salt"
        ]
    ).id("hotdog_delight:salmonsrecp")
    e.recipes.create.mixing(
        "hotdog_delight:pork_sausage",
        [
            "ratatouille:sausage_casing",
            '#forge:pork/raw',
            "#forge:salt"
        ]
    ).id("hotdog_delight:porksaurecp")
    e.recipes.create.mixing(
        "hotdog_delight:squid_ink_sausage",
        [
            "ratatouille:sausage_casing",
            'culturaldelights:squid',
            "#forge:salt"
        ]
    ).id("hotdog_delight:inksrecp")
    e.recipes.create.mixing(
        "hotdog_delight:glow_squid_ink_sausage",
        [
            "ratatouille:sausage_casing",
            'culturaldelights:glow_squid',
            "#forge:salt"
        ]
    ).id("hotdog_delight:glorecp")
})
