ServerEvents.recipes(e => {
  remove_recipes_id(e, [
    "create_central_kitchen:mixing/apple_cider",
    "create_central_kitchen:emptying/chocolate_ice_cream",
    "create_central_kitchen:emptying/strawberry_ice_cream",
    "create_central_kitchen:emptying/vanilla_ice_cream",
    "create_central_kitchen:emptying/banana_ice_cream",
    "create_central_kitchen:emptying/mint_ice_cream",
    "create_central_kitchen:emptying/adzuki_ice_cream",
    "create_central_kitchen:mixing/chocolate_ice_cream_from_fluid_chocolate",
    "create_central_kitchen:mixing/chocolate_ice_cream",
    "create_central_kitchen:mixing/strawberry_ice_cream",
    "create_central_kitchen:mixing/vanilla_ice_cream",
    "create_central_kitchen:mixing/banana_ice_cream",
    "create_central_kitchen:mixing/mint_ice_cream",
    "create_central_kitchen:mixing/adzuki_ice_cream",
    "create_central_kitchen:mixing/chocolate_milkshake",
    "create_central_kitchen:mixing/chocolate_milkshake_from_ice_cream",
    "create_central_kitchen:mixing/strawberry_milkshake",
    "create_central_kitchen:mixing/strawberry_milkshake_from_ice_cream",
    "create_central_kitchen:mixing/vanilla_milkshake",
    "create_central_kitchen:mixing/vanilla_milkshake_from_ice_cream",
    "create_central_kitchen:mixing/banana_milkshake",
    "create_central_kitchen:mixing/banana_milkshake_from_ice_cream",
    "create_central_kitchen:mixing/mint_milkshake",
    "create_central_kitchen:mixing/mint_milkshake_from_ice_cream",
    "create_central_kitchen:mixing/adzuki_milkshake",
    "create_central_kitchen:mixing/adzuki_milkshake_from_ice_cream",
    "create_central_kitchen:emptying/chocolate_milkshake",
    "create_central_kitchen:emptying/strawberry_milkshake",
    "create_central_kitchen:emptying/vanilla_milkshake",
    "create_central_kitchen:emptying/banana_milkshake",
    "create_central_kitchen:emptying/mint_milkshake",
    "create_central_kitchen:emptying/adzuki_milkshake",
    
  ])
})