StartupEvents.modifyCreativeTab("ad_astra:main", e => {
  e.remove([
    Item.of('ad_astra:tier_1_rocket', '{BotariumData:{StoredFluids:[{Amount:0L,Fluid:"minecraft:empty"}]}}').strongNBT(),
    Item.of('ad_astra:tier_2_rocket', '{BotariumData:{StoredFluids:[{Amount:0L,Fluid:"minecraft:empty"}]}}').strongNBT(),
    Item.of('ad_astra:tier_3_rocket', '{BotariumData:{StoredFluids:[{Amount:0L,Fluid:"minecraft:empty"}]}}').strongNBT(),
    Item.of('ad_astra:tier_4_rocket', '{BotariumData:{StoredFluids:[{Amount:0L,Fluid:"minecraft:empty"}]}}').strongNBT(),
    'ad_astra:etrionic_blast_furnace',
    'ad_astra:fuel_refinery',
    'ad_astra:oxygen_loader',
    'ad_astra:cryo_freezer',
    'ad_astra:etrium_ingot',
    'ad_astra:etrium_nugget',
    'ad_astra:etrium_plate',
    'ad_astra:etrium_rod',
    'ad_astra:oil_bucket',
    'ad_astra:etrium_factory_block',
    'ad_astra:encased_etrium_block',
    'ad_astra:etrium_plateblock',
    'ad_astra:etrium_panel',
    'ad_astra:etrium_block',
    "ad_astra:compressor",
    "ad_astra:nasa_workbench",
    "ad_astra:water_pump",
    "ad_astra:wrench",
    "ad_astra:steel_cable",
    "ad_astra:desh_cable",
    "ad_astra:desh_fluid_pipe",
    "ad_astra:ostrum_fluid_pipe",
    "ad_astra:cable_duct",
    "ad_astra:fluid_pipe_duct",
    "ad_astra:coal_generator",
  ])
})