StartupEvents.modifyCreativeTab("bakeries:bakeries_tab", e => {
  e.remove([
   "bakeries:blender",
   'bakeries:cheese_cube',
   'bakeries:cocoa_powder',
   'bakeries:whole_wheat_flour_bag',
   'bakeries:whole_wheat_flour',
   'bakeries:salt_scraper_rake',
   'bakeries:tomato',
   'bakeries:bottle_butter',
   'bakeries:bottle_cream',
   "bakeries:fermentation_tank",
   'bakeries:yeast_tank',
   'bakeries:cheese_tank',
   'bakeries:olive',
   'bakeries:black_white_concrete',
   'bakeries:butter_cube',
   'bakeries:flour_sieve',
   'bakeries:oven',
   'bakeries:moka_pot',
   'bakeries:moka_pot_fill',
   "bakeries:iced_american",
   "bakeries:iced_latte",
   "bakeries:brown_sugar_latte",
   "bakeries:cream_bingle_coffee",
   'bakeries:drink_cup',
   "bakeries:olive_oil",
   'bakeries:raw_coffee_bean',
   'bakeries:coffee_bean',
   'bakeries:ground_coffee',
   'bakeries:butter_flour_sand', 
   'bakeries:whole_egg', 
   'bakeries:raw_protein', 
   'bakeries:raw_egg_yolk', 
   'bakeries:fresh_cheese_cube', 
   'bakeries:cake_base',
   'bakeries:mould_two',
   'bakeries:carrot_cake',
   'bakeries:matcha_latte',
   'bakeries:coffee_table',
   'bakeries:sofa',
   'bakeries:sofa_light_gray',
   'bakeries:sofa_red'
  ])
  e.add([
   'bakeries:mould_toast',
   'bakeries:mould_cheese_cocoa_toast', 
   'bakeries:mould_pound_cake'
  ])
})
StartupEvents.modifyCreativeTab("bakeries:bakery_semi_manufactured_product_tab", e => {
  e.remove([
    'bakeries:salted_dough',
    'bakeries:cocoa_dough', 
    'bakeries:pastry',
    'bakeries:cake_paste_bucket', 
    'bakeries:egg_yolk_paste_bucket', 
    'bakeries:foamed_protein_bucket', 
    'bakeries:mould_cake_paste',
    'bakeries:mould_carrot_cake_paste',
    'bakeries:crispy_dough'
  ])
})