// 玉米乐事
StartupEvents.modifyCreativeTab("corn_delight:corn_delight", e => {
    e.remove([
      "corn_delight:cob_pipe",
      "corn_delight:corn",
      "corn_delight:corn_crate",
      "corn_delight:corn_dog",
      "corn_delight:corn_seeds",
      "corn_delight:cornbread_batter",
      "corn_delight:corncob",
      "corn_delight:creamed_corn",
      "corn_delight:grilled_corn",
      "corn_delight:nachos_bowl",
      "corn_delight:popcorn",
      "corn_delight:taco",
      "corn_delight:tortilla",
      "corn_delight:tortilla_chip",
    ])
  })
// 油炸
StartupEvents.modifyCreativeTab("create_bic_bit:bicycles_bitterballen", e => {
  e.remove([
    'create_bic_bit:unripe_cheese',
    'create_bic_bit:waxed_unripe_cheese',
    'create_bic_bit:young_cheese',
    'create_bic_bit:waxed_young_cheese',
    'create_bic_bit:aged_cheese',
    'create_bic_bit:waxed_aged_cheese',
    'create_bic_bit:unripe_cheese_wedge',
    'create_bic_bit:young_cheese_wedge',
    'create_bic_bit:aged_cheese_wedge',
    'create_bic_bit:crystallised_oil',
    'create_bic_bit:frying_oil_bottle',
    'create_bic_bit:frying_oil_bucket'
  ])
})
StartupEvents.modifyCreativeTab("frycooks_delight:frycooks_delight_tab", e => {
  e.remove([
    "frycooks_delight:burnt_morsel",
    "frycooks_delight:canola_oil",
    "frycooks_delight:fried_fish_slice",
    "frycooks_delight:fried_onion_ring",
    "frycooks_delight:hot_grease_bucket",
    "frycooks_delight:lard",
    "frycooks_delight:lard_block",
  ])
})
StartupEvents.modifyCreativeTab("create_deepfried:deepfried", e => {
  e.remove([
    "create_deepfried:apple_slices",
    "create_deepfried:chicken_nuggets",
    "create_deepfried:fish_and_chips",
    "create_deepfried:raw_chicken_nuggets",
    "create_deepfried:raw_springroll",
    "create_deepfried:springroll",
    "create_deepfried:yuca",
  ])
})
//节日乐事
StartupEvents.modifyCreativeTab("festival_delicacies:festival_delicacies", e => {
  e.remove([
    'festival_delicacies:rice',
    'festival_delicacies:red_bean'
  ])
  e.add([
      'createdelight:adzuki_beans_seed',
      "createdelight:artemisia_argyi_seed"
    ]
  )
})
// 烘焙坊
StartupEvents.modifyCreativeTab("bakeries:bakeries_tab", e => {
  e.remove([
   "bakeries:blender",
   'bakeries:cheese_cube',
   'bakeries:cocoa_powder',
   'bakeries:whole_wheat_flour_bag',
   'bakeries:whole_wheat_flour',
   'bakeries:salt_scraper_rake',
   'bakeries:salt',
   'bakeries:tomato',
   'bakeries:bottle_butter',
   'bakeries:bottle_milk',
   'bakeries:bottle_cream',
   'bakeries:yeast_tank',
   'bakeries:cheese_tank',
   'bakeries:olive',
   'bakeries:black_white_concrete',
   'bakeries:butter_cube',
   'bakeries:flour_sieve',
   'bakeries:oven',
  ])
})
StartupEvents.modifyCreativeTab("bakeries:bakery_semi_manufactured_product_tab", e => {
  e.remove([
    'bakeries:salted_dough',
    'bakeries:cocoa_dough', 
    'bakeries:pastry',
  ])
})
StartupEvents.modifyCreativeTab("vintagedelight:vintage_tab", e => {
  e.remove([
    "vintagedelight:cheese_curds"
  ])
})

//那不勒斯风味
StartupEvents.registry("minecraft:creative_mode_tab", e => {
  e.create("neapolitan:neapolitan")
  .icon(() => Item.of("neapolitan:neapolitan_ice_cream"))
  .content(() => [
    'neapolitan:banana_stalk',
    'neapolitan:carved_banana_stalk', 
    'neapolitan:frond_thatch', 
    'neapolitan:frond_thatch_stairs', 
    'neapolitan:frond_thatch_slab', 
    'neapolitan:vanilla_ice_cream_block', 
    'neapolitan:chocolate_ice_cream_block', 
    'neapolitan:strawberry_ice_cream_block', 
    'neapolitan:banana_ice_cream_block', 
    'neapolitan:mint_ice_cream_block', 
    'neapolitan:adzuki_ice_cream_block', 
    'neapolitan:vanilla_pods', 
    'neapolitan:banana_frond', 
    'neapolitan:beanstalk', 
    'neapolitan:beanstalk_thorns', 
    'neapolitan:magic_beans', 
    'neapolitan:strawberry_pips', 
    'neapolitan:mint_sprout', 
    'neapolitan:banana_bundle', 
    'neapolitan:banana_crate', 
    'neapolitan:adzuki_crate', 
    'neapolitan:roasted_adzuki_crate', 
    'neapolitan:vanilla_pod_block', 
    'neapolitan:dried_vanilla_pod_block', 
    'neapolitan:music_disc_hullabaloo', 
    'neapolitan:bananarrow', 
    'neapolitan:strawberries', 
    'neapolitan:roasted_adzuki_beans', 
    'neapolitan:mint_leaves', 
    'neapolitan:vanilla_chocolate_fingers', 
    'neapolitan:dried_vanilla_pods', 
    'neapolitan:dried_banana', 
    'neapolitan:banana', 
    'neapolitan:white_strawberries', 
    'neapolitan:chocolate_strawberries', 
    'neapolitan:chimpanzee_head',
    'neapolitan:mint_chops', 
    'neapolitan:cooked_mint_chops', 
    'neapolitan:banana_bread', 
    'neapolitan:adzuki_bun', 
    'neapolitan:vanilla_fudge', 
    'neapolitan:mint_chocolate', 
    'neapolitan:strawberry_scones', 
    'neapolitan:vanilla_cake', 
    'neapolitan:chocolate_cake', 
    'neapolitan:strawberry_cake', 
    'neapolitan:banana_cake', 
    'neapolitan:mint_cake', 
    'neapolitan:adzuki_cake', 
    'neapolitan:mint_candies', 
    'neapolitan:strawberry_bean_bonbons', 
    'neapolitan:chocolate_spider_eye', 
    'neapolitan:adzuki_stew', 
    'neapolitan:adzuki_curry', 
    'neapolitan:vanilla_pudding', 
    'neapolitan:vanilla_milkshake', 
    'neapolitan:chocolate_milkshake', 
    'neapolitan:strawberry_milkshake', 
    'neapolitan:banana_milkshake', 
    'neapolitan:mint_milkshake', 
    'neapolitan:adzuki_milkshake', 
    'neapolitan:vanilla_ice_cream', 
    'neapolitan:chocolate_ice_cream', 
    'neapolitan:strawberry_ice_cream', 
    'neapolitan:banana_ice_cream', 
    'neapolitan:mint_ice_cream', 
    'neapolitan:adzuki_ice_cream', 
    'neapolitan:neapolitan_ice_cream', 
    'neapolitan:strawberry_banana_smoothie', 
    'neapolitan:ice_cubes', 
    'neapolitan:banana_bunch', 
    'neapolitan:chimpanzee_banner_pattern',
    'neapolitan:reflection_pottery_sherd', 
    'neapolitan:scream_pottery_sherd', 
    'neapolitan:snack_pottery_sherd', 
    'neapolitan:spider_pottery_sherd', 
    'neapolitan:primal_armor_trim_smithing_template', 
    'neapolitan:plantain_spider_spawn_egg', 
    'neapolitan:chimpanzee_spawn_egg'])

  .translationKey("itemGroup.neapolitan.neapolitan")
})