ServerEvents.tags("minecraft:block", e => {
    e.removeAll("northstar:tier_1_heat_resistance")
    e.removeAll("northstar:tier_2_heat_resistance")
    e.removeAll("northstar:tier_3_heat_resistance")
    e.add("northstar:tier_1_heat_resistance",
        [
            'northstar:tungsten_block',
            'northstar:tungsten_sheetmetal',
            'northstar:tungsten_plating',
            'northstar:tungsten_pillar'])
    e.add("northstar:tier_2_heat_resistance",
        [
            'northstar:titanium_sheetmetal',
            'northstar:titanium_plating',
            'northstar:titanium_pillar'])
    e.add("northstar:tier_3_heat_resistance",
        [
            'northstar:martian_steel_sheetmetal',
            'northstar:martian_steel_plating',
            'northstar:martian_steel_pillar',
            'northstar:martian_steel_blue_lamp',
            'northstar:martian_steel_lamp',
            'northstar:martian_steel_large_plating'])
})


ServerEvents.tags("entity_type", e => {
    e.add("northstar:can_survive_cold",
        "#createdelight:can_survive_northstar"
    )
    e.add("northstar:can_survive_heat",
        "#createdelight:can_survive_northstar"
    )
    e.add("northstar:doesnt_require_oxygen",
        "#createdelight:can_survive_northstar"
    )
    e.add("createdelight:can_survive_northstar", [
        "iceandfire:mob_skull",
        "iceandfire:cyclops",
        "minecraft:sheep",     
        "minecraft:chicken",
        "iceandfire:gorgon",
        "iceandfire:deathworm",
        "iceandfire:cockatrice",
        "iceandfire:myrmex_egg",
        "iceandfire:myrmex_queen",
        "iceandfire:myrmex_royal",
        "iceandfire:myrmex_sentinel",
        "iceandfire:myrmex_soldier",
        "iceandfire:myrmex_swarmer",
        "iceandfire:myrmex_worker",
        "iceandfire:dragon_egg",
        "iceandfire:dragon_skull",
        "iceandfire:fire_dragon",
        "iceandfire:ice_dragon",
        "iceandfire:lightning_dragon",
        "iceandfire:stymphalian_bird",
        "iceandfire:amphithere",
        "iceandfire:hydra",
        "iceandfire:lightning_dragon",
        "alexsmobs:cosmic_cod",
        "alexscaves:teletor",
        "alexscaves:magnetron",
        "alexscaves:boundroid",
        "alexscaves:boundroid_winch",
        "alexscaves:ferrouslime",
        "alexscaves:notor",
        "alexscaves:nucleeper",
        "alexscaves:radgill",
        "alexscaves:brainiac",
        "alexscaves:raycat",
        "alexscaves:gammaroach",
        "alexscaves:tremorzilla"
    ])
})