StartupEvents.registry("block", e => {
    e.create("createdelight:adzuki_beans", "crop")
        .age(6, age => {
            age.shape(0, 0, 0, 0, 16, 2, 16)
            age.shape(1, 0, 0, 0, 16, 4, 16)
            age.shape(2, 0, 0, 0, 16, 8, 16)
            age.shape(3, 0, 0, 0, 16, 12, 16)
            age.shape(4, 0, 0, 0, 16, 12, 16)
            age.shape(5, 0, 0, 0, 16, 16, 16)
            age.shape(6, 0, 0, 0, 16, 16, 16)
        })
        .growTick((tickevent) => 3)
        .bonemeal(info => info.random.nextInt(2))
        .dropSeed(true)
        .crop("createdelight:adzuki_beans_seed", 1)
        .texture(0, "neapolitan:block/flowering_adzuki_sprouts_stage0")
        .texture(1, "neapolitan:block/flowering_adzuki_sprouts_stage1")
        .texture(2, "neapolitan:block/flowering_adzuki_sprouts_stage2")
        .texture(3, "neapolitan:block/flowering_adzuki_sprouts_stage3")
        .texture(4, "neapolitan:block/flowering_adzuki_sprouts_stage4")
        .texture(5, "neapolitan:block/flowering_adzuki_sprouts_stage5")
        .texture(6, "neapolitan:block/flowering_adzuki_sprouts_stage6")
        .item(seed => {
            seed.texture("neapolitan:item/adzuki_beans")
            seed.translationKey("item.createdelight.adzuki_beans_seed")
        })
        .renderType("cutout")
        .translationKey("block.createdelight.adzuki_beans")
    e.create("createdelight:artemisia_argyi", "crop")
        .age(3, age => {
            age.shape(0, 0, 0, 0, 16, 2, 16)
            age.shape(1, 0, 0, 0, 16, 4, 16)
            age.shape(2, 0, 0, 0, 16, 8, 16)
            age.shape(3, 0, 0, 0, 16, 12, 16)
        })
        .growTick((tickevent) => 3)
        .bonemeal(info => info.random.nextInt(2))
        .dropSeed(true)
        .crop('festival_delicacies:artemisia_argyi', 1)
        .crop('festival_delicacies:artemisia_argyi', 0.5)
        .texture(0, "createdelight:block/artemisia_argyi_stage0")
        .texture(1, "createdelight:block/artemisia_argyi_stage1")
        .texture(2, "createdelight:block/artemisia_argyi_stage2")
        .texture(3, "createdelight:block/artemisia_argyi_stage3")
        .item(seed => {
            seed.texture("createdelight:item/artemisia_argyi_seed")
            seed.translationKey("item.createdelight.adzuki_beans_seed")
        })
        .renderType("cutout")
        .translationKey("block.createdelight.artemisia_argyi")

})
