JEIEvents.hideItems(e => {
    e.hide([
        "create_sa:drone_controller",
        "create_sa:brass_drone_item",
        "create_sa:copper_magnet",
        "create_sa:fan_component",
        "create_sa:vault_component",
        "create_sa:block_picker",
        "create_sa:brass_cube",
        "ad_astra:compressor",
        "ad_astra:nasa_workbench",
        "ad_astra:water_pump",
        "ad_astra:wrench",
        "ad_astra:steel_cable",
        "ad_astra:desh_cable",
        "ad_astra:desh_fluid_pipe",
        "ad_astra:ostrum_fluid_pipe",
        "ad_astra:cable_duct",
        "ad_astra:fluid_pipe_duct",
        "ad_astra:coal_generator",
        "ad_astra:iron_plate",
        "ad_astra:steel_plate",
        "ad_astra:iron_rod",
        "ad_astra:steel_ingot",
        "alloyedguns:musket",
        "alloyedguns:flintlock",
        "cgm:workbench",
        "create_enchantment_industry:experience_rotor",
        "cgm:crude_shot",
        "alloyedguns:complex_bullet_casing",
        "alloyedguns:complex_bullet",
        "alloyedguns:small_iron_pipe",
        "vinery:cherry_boat",
        "beachparty:palm_boat",
        "beachparty:palm_chest_boat",
        "vinery:cherry_chest_boat",
        "create_sa:block_picker",
        "refinedstorage:wrench",
        "refinedstorage:raw_basic_processor",
        "refinedstorage:raw_improved_processor",
        "refinedstorage:raw_advanced_processor",
        'quark:potato_crate',
        'createaddition:diamond_grit',
        'ad_astra:steel_block'
    ])
})
JEIEvents.addFluids(e => {
    e.add([
        "ratatouille:egg_yolk"
    ])
})