JEIEvents.hideItems((e) => {
  e.hide([
    "ad_astra:compressor",
    "ad_astra:nasa_workbench",
    "ad_astra:water_pump",
    "ad_astra:wrench",
    "ad_astra:steel_cable",
    "ad_astra:desh_cable",
    "ad_astra:desh_fluid_pipe",
    "ad_astra:ostrum_fluid_pipe",
    "ad_astra:cable_duct",
    "ad_astra:fluid_pipe_duct",
    "ad_astra:coal_generator",
    "ad_astra:iron_plate",
    "ad_astra:iron_rod",
    "ad_astra:steel_ingot",
    "quark:potato_crate",
    "createaddition:diamond_grit",
    "ad_astra:steel_block",
    "ae2:facade",
    "megacells:mega_interface",
    "megacells:mega_pattern_provider",
    "megacells:mega_interface_interface",
    "megacells:mega_pattern_provider_interface",
    "iceandfire:dragonsteel_fire_sword",
    "iceandfire:dragonsteel_fire_pickaxe",
    "iceandfire:dragonsteel_fire_axe",
    "iceandfire:dragonsteel_fire_shovel",
    "iceandfire:dragonsteel_fire_hoe",
    "iceandfire:dragonsteel_ice_pickaxe",
    "iceandfire:dragonsteel_ice_sword",
    "iceandfire:dragonsteel_ice_axe",
    "iceandfire:dragonsteel_ice_shovel",
    "iceandfire:dragonsteel_ice_hoe",
    "iceandfire:dragonsteel_lightning_sword",
    "iceandfire:dragonsteel_lightning_pickaxe",
    "iceandfire:dragonsteel_lightning_axe",
    "iceandfire:dragonsteel_lightning_shovel",
    "iceandfire:dragonsteel_lightning_hoe"
  ]);
});

JEIEvents.addItems((e) => {
  e.add([
    "create_connected:fan_freezing_catalyst"
  ]);
});
