Ponder.tags(event => {
    event.createTag(
        "createdelight:ae2",
        "ae2:controller",
        "应用能源2",
        "集存储，物流，自动化一身的强大mod",
        [
            "ae2:interface", 
            "ae2:pattern_provider", 
            "ae2:storage_bus", 
            "ae2:certus_quartz_crystal", 
            "ae2:annihilation_plane", 
            "ae2:formation_plane",
            "ae2:fluix_glass_cable",
            "ae2:fluix_covered_cable",
            "ae2:fluix_covered_dense_cable",
            "ae2:fluix_smart_cable",
            "ae2:fluix_smart_dense_cable",
            "ae2:io_port",
            "ae2:import_bus",
            "ae2:export_bus"]
    )
})