
["Common Config"]
	#Capacity of Tools requiring Fluids in mB
	"Capacity of Tools requiring Fluids" = 2000
	#Tool Capacity Enchantment Capacity Addition in mB
	"Capacity Addition of Tools with Capacity Enchantment" = 1000

