#Whether to enable the drop report
disableDropReport = true
#Threshold for drop reporting.
#Range: > 0
itemThreshold = 100
#If this option is enabled, the drop report will be counted by a single drop entity, not by the number of items in it
ignoreStackCount = false
#Money Chain used for money calculating
moneyChain = "main"
#Whether to use money for teleporting
useMoneyTeleport = true
#Coin used for waystone teleporting per unit.
#It's the base value of the chain.
#Range: > 1
teleportCost = 45
#The chance for luna soil to boost crops grows.
#Range: 0.0 ~ 1.0
lunaSoilBoostChance = 0.5

