
[air]
	#Range: > 1
	uses_per_tank = 36000
	#Range: > 1
	uses_per_tank_hover = 72000

[speed]
	#Range: 0.01 ~ 100.0
	horizontal = 0.06
	#Range: 0.01 ~ 100.0
	vertical = 0.4
	#Range: 0.01 ~ 100.0
	acceleration = 0.6
	#Range: -100.0 ~ 0.0
	hover_descend = 0.0
	#Range: 0.0 ~ 100.0
	swim_modifier = 1.8

[features]
	#Range: 1.0 ~ 100.0
	elytra_boost = 1.25

[enchantments]
	list = []
	is_blacklist = true

