ServerEvents.tags("minecraft:item", e => {
    e.add("createdelight:cafe", [
        'createcafe:iced_coffee',
        'createcafe:iced_coffee_milk',
        'createcafe:caramel_iced_coffee',
        'createcafe:banana_iced_coffee'])
    e.add("createdelight:milk_tea", [
        'createcafe:pineapple_milk_tea',
        'createcafe:blueberry_milk_tea',
        'createcafe:lychee_milk_tea',
        'createcafe:grape_milk_tea',
        'createcafe:fig_milk_tea',
        'createcafe:durian_milk_tea',
        'createcafe:peach_milk_tea',
        'createcafe:mango_milk_tea',
        'createcafe:banana_milk_tea',
        'createcafe:watermelon_milk_tea',
        'createcafe:lemon_milk_tea',
        'createcafe:persimmon_milk_tea',
        'createcafe:orange_milk_tea',
        'createcafe:kiwi_milk_tea',
        'createcafe:sweetberry_milk_tea',
        'createcafe:pumpkin_milk_tea',
        'createcafe:apple_milk_tea',
        'createcafe:cherry_milk_tea',
        'createcafe:oreo_milk_tea'])

    e.add("create:upright_on_belt", [
        'createcafe:pineapple_milk_tea',
        'createcafe:blueberry_milk_tea',
        'createcafe:lychee_milk_tea',
        'createcafe:grape_milk_tea',
        'createcafe:fig_milk_tea',
        'createcafe:durian_milk_tea',
        'createcafe:peach_milk_tea',
        'createcafe:mango_milk_tea',
        'createcafe:banana_milk_tea',
        'createcafe:watermelon_milk_tea',
        'createcafe:lemon_milk_tea',
        'createcafe:persimmon_milk_tea',
        'createcafe:orange_milk_tea',
        'createcafe:kiwi_milk_tea',
        'createcafe:sweetberry_milk_tea',
        'createcafe:pumpkin_milk_tea',
        'createcafe:apple_milk_tea',
        'createcafe:cherry_milk_tea',
        'createcafe:oreo_milk_tea',
        'createcafe:iced_coffee',
        'createcafe:iced_coffee_milk',
        'createcafe:caramel_iced_coffee',
        'createcafe:banana_iced_coffee',
        'createcafe:iced_coffee_cup',
        'createcafe:iced_coffee_cup_ice',
        'createcafe:boba_cup',
        'createcafe:empty_boba_cup'])
    e.add("forge:coffee_grounds", "createcafe:coffee_grounds")
})