ServerEvents.recipes(e => {
    //安山合金
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems('2x #forge:nuggets/iron', 'minecraft:andesite')
        .outputItems('3x create:andesite_alloy')
        .inputFE(1000)
        .id("create_delight:alloy_electric_furnace/andesite_alloy_iron")
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems('2x #forge:nuggets/zinc', 'minecraft:andesite')
        .outputItems('3x create:andesite_alloy')
        .inputFE(1000)
        .id("create_delight:alloy_electric_furnace/andesite_alloy_zinc")
    //赤钕合金锭
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("2x #forge:ingots/iron", "2x alexscaves:raw_scarlet_neodymium")
        .outputItems("alexscaves:scarlet_neodymium_ingot")
        .inputFE(2000)
        .id("create_delight:alloy_electric_furnace/scarlet_neodymium")
    //青钕合金锭
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("2x #forge:ingots/iron", "2x alexscaves:raw_azure_neodymium")
        .outputItems("alexscaves:azure_neodymium_ingot")
        .inputFE(2000)
        .id("create_delight:alloy_electric_furnace/azure_neodymium")
    //琥珀金锭
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:ingots/gold", "#forge:ingots/silver")
        .outputItems("2x createaddition:electrum_ingot")
        .inputFE(2500)
        .id("create_delight:alloy_electric_furnace/electrum")
    //青铜锭
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("3x #forge:ingots/copper", "#forge:ingots/tin")
        .outputItems("4x createdelightcore:bronze_ingot")
        .inputFE(2500)
        .id("create_delight:alloy_electric_furnace/bronze")
    //黄铜锭
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:ingots/copper", "#forge:ingots/zinc")
        .outputItems("2x create:brass_ingot")
        .inputFE(2500)
        .id("create_delight:alloy_electric_furnace/brass")
    //钢锭
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("3x #forge:ingots/iron", "createmetallurgy:coke")
        .outputItems("3x createmetallurgy:steel_ingot")
        .inputFE(3000)
        .id("create_delight:alloy_electric_furnace/steel")
    //下界合金锭
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("3x #forge:ingots/gold", "3x minecraft:netherite_scrap")
        .outputItems("minecraft:netherite_ingot")
        .inputFE(3000)
        .id("create_delight:alloy_electric_furnace/netherite")
    //下界钢锭
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("minecraft:netherite_ingot", "createmetallurgy:steel_ingot")
        .outputItems("2x createbigcannons:nethersteel_ingot")
        .inputFE(4000)
        .id("create_delight:alloy_electric_furnace/nethersteel")
    //坚钢锭
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems('3x #forge:ingots/steel', '2x #forge:ingots/tungsten')
        .outputItems('5x #forge:ingots/obdurium')
        .inputFE(4000)
        .id("create_delight:alloy_electric_furnace/obdurium")
    //虚空钢
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems('#forge:ingots/steel', '#forge:dusts/ender_pearl')
        .outputItems('createutilities:void_steel_ingot')
        .inputFE(4000)
        .id("create_delight:alloy_electric_furnace/void_steel")


    //粉熔炼
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:dusts/iron")
        .outputItems("minecraft:iron_ingot")
        .inputFE(1000)
        .id("create_delight:alloy_electric_furnace/iron")
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:dusts/gold")
        .outputItems("minecraft:gold_ingot")
        .inputFE(1000)
        .id("create_delight:alloy_electric_furnace/gold")
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:dusts/copper")
        .outputItems("minecraft:copper_ingot")
        .inputFE(1000)
        .id("create_delight:alloy_electric_furnace/copper")
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:dusts/silver")
        .outputItems("iceandfire:silver_ingot")
        .inputFE(1000)
        .id("create_delight:alloy_electric_furnace/silver")
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:dusts/zinc")
        .outputItems("create:zinc_ingot")
        .inputFE(1000)
        .id("create_delight:alloy_electric_furnace/zinc")
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:dusts/tin")
        .outputItems("createdelightcore:tin_ingot")
        .inputFE(1000)
        .id("create_delight:alloy_electric_furnace/tin")
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:dusts/desh")
        .outputItems("ad_astra:desh_ingot")
        .inputFE(500)
        .id("create_delight:alloy_electric_furnace/desh")
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:dusts/ostrum")
        .outputItems("ad_astra:ostrum_ingot")
        .inputFE(1000)
        .id("create_delight:alloy_electric_furnace/ostrum")
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:dusts/calorite")
        .outputItems("ad_astra:calorite_ingot")
        .inputFE(4000)
        .id("create_delight:alloy_electric_furnace/calorite")
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:dusts/tungsten")
        .outputItems("createmetallurgy:tungsten_ingot")
        .inputFE(3000)
        .id("create_delight:alloy_electric_furnace/tungsten")
})