ServerEvents.recipes(e => {
    //下界钢锭
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("minecraft:netherite_ingot", "createmetallurgy:steel_ingot")
        .outputItems("2x createbigcannons:nethersteel_ingot")
        .inputFE(1000)
    //赤钕合金锭
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("2x #forge:ingots/iron", "2x alexscaves:raw_scarlet_neodymium")
        .outputItems("alexscaves:scarlet_neodymium_ingot")
        .inputFE(1000)
    //青钕合金锭
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("2x #forge:ingots/iron", "2x alexscaves:raw_azure_neodymium")
        .outputItems("alexscaves:azure_neodymium_ingot")
        .inputFE(1000)
    //下界合金锭
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("3x #forge:ingots/gold", "3x minecraft:netherite_scrap")
        .outputItems("minecraft:netherite_ingot")
        .inputFE(1000)
    //琥珀金锭
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:ingots/gold", "#forge:ingots/silver")
        .outputItems("4x createaddition:electrum_ingot")
        .inputFE(1000)
    //青铜锭
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("3x #forge:ingots/copper", "#forge:ingots/tin")
        .outputItems("4x createdelightcore:bronze_ingot")
        .inputFE(1000)
    //钢锭
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("3x #forge:ingots/iron", "createmetallurgy:coke")
        .outputItems("3x createmetallurgy:steel_ingot")
        .inputFE(1000)
    //黄铜锭
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:ingots/copper", "#forge:ingots/zinc")
        .outputItems("2x create:brass_ingot")
        .inputFE(1000)
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:dusts/iron")
        .outputItems("minecraft:iron_ingot")
        .inputFE(1000)
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:dusts/gold")
        .outputItems("minecraft:gold_ingot")
        .inputFE(1000)
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:dusts/copper")
        .outputItems("minecraft:copper_ingot")
        .inputFE(1000)
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:dusts/silver")
        .outputItems("iceandfire:silver_ingot")
        .inputFE(1000)
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:dusts/zinc")
        .outputItems("create:zinc_ingot")
        .inputFE(1000)
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:dusts/tin")
        .outputItems("createdelightcore:tin_ingot")
        .inputFE(1000)
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:dusts/desh")
        .outputItems("ad_astra:desh_ingot")
        .inputFE(1000)
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:dusts/ostrum")
        .outputItems("ad_astra:ostrum_ingot")
        .inputFE(1000)
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:dusts/calorite")
        .outputItems("ad_astra:calorite_ingot")
        .inputFE(1000)
    e.recipes.createdelight.alloy_electric_furnace()
        .inputItems("#forge:dusts/tungsten")
        .outputItems("createmetallurgy:tungsten_ingot")
        .inputFE(1000)
})