
#Please be advised that certain season-related options are world-specific and are located in <Path to your world folder>/serverconfig/sereneseasons-server.toml.
[weather_settings]
	#Generate snow and ice during the Winter season
	generate_snow_ice = false
	#Change the frequency of rain/snow/storms based on the season
	change_weather_frequency = true

[time_settings]
	#The duration of a Minecraft day in ticks.
	#This only adjusts the internal length of a day used by the season cycle.
	#It is intended to be used in conjunction with another mod which adjusts the actual length of a Minecraft day.
	day_duration = 24000
	#The duration of a sub season in days.
	sub_season_duration = 8
	#The starting sub season for new worlds.
	#0 = Random, 1 - 3 = Early/Mid/Late Spring
	#4 - 6 = Early/Mid/Late Summer
	#7 - 9 = Early/Mid/Late Autumn
	#10 - 12 = Early/Mid/Late Winter
	starting_sub_season = 1
	#If the season should progress on a server with no players online
	progress_season_while_offline = false

[aesthetic_settings]
	#Change the grass color based on the current season
	change_grass_color = true
	#Change the foliage colour based on the current season
	change_foliage_color = true
	#Change the birch colour based on the current season
	change_birch_color = true

[dimension_settings]
	#Seasons will only apply to dimensons listed here
	whitelisted_dimensions = ["minecraft:overworld"]

#melt_percent is the 0-1 percentage chance a snow or ice block will melt when chosen. (e.g. 100.0 = 100%, 50.0 = 50%)
#melt_rolls is the number of blocks randomly picked in each chunk, each tick. (High number rolls is not recommended on servers)
#melt_rolls should be 0 if blocks should not melt in that season.
#biome_temp_adjustment is the amount to adjust the biome temperature by from -10.0 to 10.0.
#min_rain_time is the minimum time interval between rain events in ticks. Set to -1 to disable rain.
#max_rain_time is the maximum time interval between rain events in ticks. Set to -1 to disable rain.
#min_thunder_time is the minimum time interval between thunder events in ticks. Set to -1 to disable thunder.
#max_thunder_time is the maximum time interval between thunder events in ticks. Set to -1 to disable thunder.
#grass_colour is the color of grass, from 0 to 0xFFFFFF(16777215).
#grass_saturation is the saturation multiplier of grass color. Set to -1 to disable.
#foliage_colour is the color of foliage, from 0 to 0xFFFFFF(16777215).
#foliage_saturation is the saturation multiplier of foliage color. Set to -1 to disable.
#birch_color is the color of birch foliage, from 0 to 0xFFFFFF(16777215). It will use the same saturation multiplier of foliage_colour
[[season_properties]]
	season = "LATE_WINTER"
	melt_percent = 0.0
	melt_rolls = 0
	biome_temp_adjustment = -0.8
	min_rain_time = 12000
	max_rain_time = 36000
	min_thunder_time = -1
	max_thunder_time = -1
	grass_colour = 9339265
	grass_saturation = 0.6
	foliage_colour = 10842224
	foliage_saturation = 0.6
	birch_color = 9409119

[[season_properties]]
	season = "MID_SPRING"
	melt_percent = 8.33
	melt_rolls = 1
	biome_temp_adjustment = 0.0
	min_rain_time = 12000
	max_rain_time = 96000
	min_thunder_time = 12000
	max_thunder_time = 180000
	grass_colour = 6783639
	grass_saturation = -1.0
	foliage_colour = 5211823
	foliage_saturation = -1.0
	birch_color = 7254659

[[season_properties]]
	season = "EARLY_AUTUMN"
	melt_percent = 12.5
	melt_rolls = 1
	biome_temp_adjustment = 0.0
	min_rain_time = 12000
	max_rain_time = 180000
	min_thunder_time = 12000
	max_thunder_time = 180000
	grass_colour = 9400175
	grass_saturation = -1.0
	foliage_colour = 12861504
	foliage_saturation = -1.0
	birch_color = 11641922

[[season_properties]]
	season = "MID_AUTUMN"
	melt_percent = 8.33
	melt_rolls = 1
	biome_temp_adjustment = 0.0
	min_rain_time = 12000
	max_rain_time = 180000
	min_thunder_time = 12000
	max_thunder_time = 180000
	grass_colour = 10444639
	grass_saturation = -1.0
	foliage_colour = 15671585
	foliage_saturation = -1.0
	birch_color = 14852657

[[season_properties]]
	season = "EARLY_WINTER"
	melt_percent = 0.0
	melt_rolls = 0
	biome_temp_adjustment = -0.8
	min_rain_time = 12000
	max_rain_time = 36000
	min_thunder_time = -1
	max_thunder_time = -1
	grass_colour = 11489103
	grass_saturation = 0.6
	foliage_colour = 14364720
	foliage_saturation = 0.6
	birch_color = 11629115

[[season_properties]]
	season = "LATE_SPRING"
	melt_percent = 12.5
	melt_rolls = 1
	biome_temp_adjustment = 0.0
	min_rain_time = 12000
	max_rain_time = 96000
	min_thunder_time = 12000
	max_thunder_time = 180000
	grass_colour = 7307663
	grass_saturation = -1.0
	foliage_colour = 6259871
	foliage_saturation = -1.0
	birch_color = 7646835

[[season_properties]]
	season = "EARLY_SUMMER"
	melt_percent = 25.0
	melt_rolls = 1
	biome_temp_adjustment = 0.0
	min_rain_time = 12000
	max_rain_time = 96000
	min_thunder_time = 12000
	max_thunder_time = 180000
	grass_colour = 7831687
	grass_saturation = -1.0
	foliage_colour = 7307663
	foliage_saturation = -1.0
	birch_color = 8039012

[[season_properties]]
	season = "LATE_AUTUMN"
	melt_percent = 6.25
	melt_rolls = 1
	biome_temp_adjustment = -0.25
	min_rain_time = 12000
	max_rain_time = 180000
	min_thunder_time = 12000
	max_thunder_time = 180000
	grass_colour = 11489103
	grass_saturation = 0.85
	foliage_colour = 14364720
	foliage_saturation = 0.85
	birch_color = 13208117

[[season_properties]]
	season = "MID_WINTER"
	melt_percent = 0.0
	melt_rolls = 0
	biome_temp_adjustment = -0.8
	min_rain_time = 12000
	max_rain_time = 36000
	min_thunder_time = -1
	max_thunder_time = -1
	grass_colour = 11489103
	grass_saturation = 0.45
	foliage_colour = 14364720
	foliage_saturation = 0.45
	birch_color = 10519117

[[season_properties]]
	season = "LATE_SUMMER"
	melt_percent = 25.0
	melt_rolls = 1
	biome_temp_adjustment = 0.0
	min_rain_time = 12000
	max_rain_time = 96000
	min_thunder_time = 12000
	max_thunder_time = 180000
	grass_colour = 8877943
	grass_saturation = -1.0
	foliage_colour = 10444639
	foliage_saturation = -1.0
	birch_color = 10003787

[[season_properties]]
	season = "MID_SUMMER"
	melt_percent = 25.0
	melt_rolls = 1
	biome_temp_adjustment = 0.0
	min_rain_time = 12000
	max_rain_time = 96000
	min_thunder_time = 12000
	max_thunder_time = 180000
	grass_colour = 16777215
	grass_saturation = -1.0
	foliage_colour = 16777215
	foliage_saturation = -1.0
	birch_color = 8431445

[[season_properties]]
	season = "EARLY_SPRING"
	melt_percent = 6.25
	melt_rolls = 1
	biome_temp_adjustment = -0.25
	min_rain_time = 12000
	max_rain_time = 96000
	min_thunder_time = 12000
	max_thunder_time = 180000
	grass_colour = 7831687
	grass_saturation = 0.85
	foliage_colour = 7307663
	foliage_saturation = 0.85
	birch_color = 8821352

