ServerEvents.tags("block", e => {
    e.add("quality_food:quality_blocks",
        'brewinandchewin:flaxen_cheese_wheel',
        'youkaishomecoming:chest_of_heart_throbbing_surprise', 
        'youkaishomecoming:flesh_feast', 
        'youkaishomecoming:red_velvet_cake', 
        'youkaishomecoming:tarte_lune', 
        'dungeonsdelight:glow_berry_gelatin_block', 
        'dungeonsdelight:ossobusco_block', 
        'dungeonsdelight:guardian_angel_block', 
        'dungeonsdelight:spider_pie', 
        'dungeonsdelight:monster_cake', 
        'ends_delight:dragon_leg_with_sauce_block', 
        'ends_delight:grilled_shulker_block', 
        'ends_delight:steamed_dragon_egg_block', 
        'ends_delight:dragon_meat_stew_block', 
        'cavedelight:roasted_grottoceratops', 
        'cavedelight:boiled_trilocaris', 
        'cavedelight:roasted_dino_chop', 
        'cavedelight:pinenut_pie', 
        'cavedelight:tectonic_cheesecake', 
        'trailandtales_delight:cherry_cake', 
        'trailandtales_delight:cherry_cheese_pie', 
        'trailandtales_delight:cooked_sniffer_egg_block', 
        'trailandtales_delight:stuffed_sniffer_egg_block', 
        'farmersrespite:coffee_cake', 
        'mynethersdelight:magma_cake', 
        'mynethersdelight:ghasta_with_cream', 
        'mynethersdelight:roast_stuffed_hoglin', 
        'oceanic_delight:sponge_cake', 
        'oceanic_delight:stuffed_pufferfish', 
        'oceanic_delight:paella_plate', 
        'silentsdelight:sculk_catalyst_pie',
    )
    Ingredient.of([
        "@vintagedelight",
        "@culturaldelights",
        "@fruitsdelight",
        "@collectorsreap",
        "@cratedelight",
        "@neapolitan",
        "@mynethersdelight",
        "@oceanic_delight",
        "@frycooks_delight",
        "@corn_delight",
        "@youkaishomecoming",
        "@nethervinery",
        "@dungeonsdelight",
        "@ends_delight",
        "@crabbersdelight"
    ]).stacks.forEach(item => {
        if ((item.id.endsWith("_crate") || item.id.endsWith("_bag") || item.id.endsWith("_barrel")) && item.block) {
            e.add("quality_food:quality_blocks", item.id)
        }
    })
    e.add("createdelight:quality_crops",
        "neapolitan:vanilla_vine",
        "neapolitan:strawberry_bush",
        "neapolitan:small_banana_frond",
        "neapolitan:banana_frond",
        "neapolitan:large_banana_frond",
        "neapolitan:mint",
        "vinery:red_grape_bush",
        "vinery:white_grape_bush",
        "vinery:savanna_grape_bush_red",
        "vinery:savanna_grape_bush_white",
        "vinery:taiga_grape_bush_red",
        "vinery:taiga_grape_bush_white",
        "vinery:jungle_grape_bush_red",
        "vinery:jungle_grape_bush_white",
        "nethervinery:crimson_grape_bush",
        "nethervinery:warped_grape_bush",
        "minecraft:cocoa",
        "minecraft:sugar_cane",
        "farmersdelight:budding_tomatoes",
        "farmersdelight:tomatoes",
        'fruitsdelight:bayberry_leaves',
        'fruitsdelight:kiwi_leaves',
        'fruitsdelight:fig_leaves',
        'fruitsdelight:durian_leaves',
        'fruitsdelight:pear_leaves',
        'fruitsdelight:hawberry_leaves',
        'fruitsdelight:lychee_leaves',
        'fruitsdelight:mango_leaves',
        'fruitsdelight:persimmon_leaves',
        'fruitsdelight:peach_leaves',
        'fruitsdelight:orange_leaves', 
        'fruitsdelight:apple_leaves',
        'fruitsdelight:mangosteen_leaves',
        'farmersdelight:brown_mushroom_colony',
        'farmersdelight:red_mushroom_colony',
        'mynethersdelight:crimson_fungus_colony',
        'mynethersdelight:warped_fungus_colony',
        'collectorsreap:portobello_colony',
        'minecraft:sweet_berry_bush',
        "nethervinery:crimson_grape_bush",
        "nethervinery:warped_grape_bush",
        "collectorsreap:pomegranate_bush",
        "collectorsreap:lime_bush",
        "culturaldelights:corn",
        "culturaldelights:corn_upper",
        "fruitsdelight:lemon_tree",
        "fruitsdelight:blueberry_bush",
        "fruitsdelight:cranberry_bush",
        'mynethersdelight:powdery_cane',
        'mynethersdelight:powdery_cannon',
        'mynethersdelight:bullet_pepper'
    )
    e.add("quality_food:quality_blocks", 
        "#createdelight:quality_crops",
        "minecraft:sea_pickle"
    )
    e.remove("quality_food:quality_blocks", 
        "#farmersdelight:wild_crops",
    )
})

ServerEvents.tags("item", e => {
    e.add("createdelightcore:life_matter", [
        "createdelight:life_matter"
    ])
    e.add("createdelight:life_matter", [
        "createdelight:life_matter"
    ])

    // 按“直接收割得到、仍可作为基础食材/原料”的身份维护；不要复用 quality_food:material_whitelist。
    // 多产出原料可以加入；种子、粉类、面团、料理、容器和加工中间品不加入。
    const lifeMatterSources = [
        "minecraft:wheat",
        "minecraft:carrot",
        "minecraft:potato",
        "minecraft:beetroot",
        "minecraft:sugar_cane",
        "minecraft:cocoa_beans",
        "minecraft:sweet_berries",
        "minecraft:apple",
        "minecraft:brown_mushroom",
        "minecraft:red_mushroom",
        "minecraft:crimson_fungus",
        "minecraft:warped_fungus",
        "farmersdelight:cabbage",
        "farmersdelight:onion",
        "farmersdelight:rice",
        "farmersdelight:tomato",
        "farmersdelight:brown_mushroom_colony",
        "farmersdelight:red_mushroom_colony",
        "mynethersdelight:crimson_fungus_colony",
        "mynethersdelight:warped_fungus_colony",
        "mynethersdelight:bullet_pepper",
        "culturaldelights:corn_cob",
        "neapolitan:banana",
        "neapolitan:mint_leaves",
        "neapolitan:vanilla_pods",
        "neapolitan:strawberries",
        "neapolitan:white_strawberries",
        "vinery:red_grape",
        "vinery:white_grape",
        "vinery:savanna_grapes_red",
        "vinery:savanna_grapes_white",
        "vinery:taiga_grapes_red",
        "vinery:taiga_grapes_white",
        "vinery:jungle_grapes_red",
        "vinery:jungle_grapes_white",
        "nethervinery:crimson_grape",
        "nethervinery:warped_grape",
        "fruitsdelight:bayberry",
        "fruitsdelight:blueberry",
        "fruitsdelight:cranberry",
        "fruitsdelight:durian",
        "fruitsdelight:fig",
        "fruitsdelight:hawberry",
        "fruitsdelight:kiwi",
        "fruitsdelight:lemon",
        "fruitsdelight:lychee",
        "fruitsdelight:mango",
        "fruitsdelight:mangosteen",
        "fruitsdelight:orange",
        "fruitsdelight:peach",
        "fruitsdelight:pear",
        "fruitsdelight:persimmon",
        "collectorsreap:pomegranate",
        "collectorsreap:lime",
        "collectorsreap:portobello",
        "collectorsreap:portobello_colony",
        "frycooks_delight:canola",
        "frycooks_delight:canola_seeds",
        "createdelight:adzuki_beans_seed",
        "festival_delicacies:chinese_cabbage",
        "festival_delicacies:greenonion",
        "festival_delicacies:eggplant",
        "festival_delicacies:garlic_chive",
        "festival_delicacies:fennel",
        "festival_delicacies:jujube",
        "festival_delicacies:olive",
        "festival_delicacies:walnut",
        "trailandtales_delight:pitcher_plant",
        "trailandtales_delight:lantern_fruit",
        "oceanic_delight:sea_grape",
        "youkaishomecoming:mandrake_root",
        "youkaishomecoming:pods",
        "youkaishomecoming:udumbara_flower",
        "createcafe:coffee_fruit",
        "vintagedelight:cucumber",
        "miners_delight:cave_carrot",
        "cosmopolitan:arbutus_berries",
        "cosmopolitan:wildberry",
        "youkaishomecoming:soybean"
    ]
    e.add("createdelightcore:life_matter_sources", lifeMatterSources)
    e.add("createdelight:life_matter_sources", lifeMatterSources)

    const qualityHarvestCalibrators = [
        "createdelight:quality_harvest_calibrator_tier_1",
        "createdelight:quality_harvest_calibrator_tier_2",
        "createdelight:quality_harvest_calibrator_tier_3"
    ]
    e.add("createdelightcore:quality_harvest_calibrators", qualityHarvestCalibrators)
    e.add("createdelight:quality_harvest_calibrators", qualityHarvestCalibrators)
    e.add("createdelightcore:quality_harvest_calibrators/tier_1", [
        "createdelight:quality_harvest_calibrator_tier_1"
    ])
    e.add("createdelight:quality_harvest_calibrators/tier_1", [
        "createdelight:quality_harvest_calibrator_tier_1"
    ])
    e.add("createdelightcore:quality_harvest_calibrators/tier_2", [
        "createdelight:quality_harvest_calibrator_tier_2"
    ])
    e.add("createdelight:quality_harvest_calibrators/tier_2", [
        "createdelight:quality_harvest_calibrator_tier_2"
    ])
    e.add("createdelightcore:quality_harvest_calibrators/tier_3", [
        "createdelight:quality_harvest_calibrator_tier_3"
    ])
    e.add("createdelight:quality_harvest_calibrators/tier_3", [
        "createdelight:quality_harvest_calibrator_tier_3"
    ])

    e.remove("quality_food:material_whitelist", 
        "#farmersdelight:wild_crops"
    )
    const iceCreamScoops = []
    Ingredient.of(["@alexscaves", "@createdelightcore"]).stacks.forEach(item => {
        if (item.id.endsWith("_ice_cream_scoop")) {
            iceCreamScoops.push(item.id)
        }
    })
    const vineryQualityFoods = []
    const vineryQualityFoodIds = [
        "vinery:mead",
        "vinery:creepers_crush",
        "vinery:jo_special_mixture",
        "vinery:eiswein",
        "vinery:villagers_fright",
        "vinery:bottle_mojang_noir"
    ]
    const vineryQualityFoodSuffixes = [
        "_wine",
        "_grapejuice",
        "_juice",
        "_cider",
        "_fizz",
        "_nectar",
        "_grenache",
        "_pinot"
    ]
    Ingredient.of(["@vinery", "@nethervinery"]).stacks.forEach(item => {
        if (vineryQualityFoodIds.includes(item.id) || vineryQualityFoodSuffixes.some(suffix => item.id.endsWith(suffix))) {
            vineryQualityFoods.push(item.id)
        }
    })
    e.add("quality_food:material_whitelist", iceCreamScoops)
    e.add("quality_food:material_whitelist", vineryQualityFoods)
    e.add("quality_food:material_whitelist", [
        'create:dough',
        'bakeries:pizza_flatbread',
        'farmersdelight:brown_mushroom_colony',
        'farmersrespite:coffee_berries',
        'farmersrespite:coffee_beans',
        'farmersrespite:green_tea_leaves',
        'farmersrespite:yellow_tea_leaves',
        'farmersrespite:black_tea_leaves',
        'farmersdelight:red_mushroom_colony', 
        'mynethersdelight:crimson_fungus_colony', 
        'mynethersdelight:warped_fungus_colony', 
        'collectorsreap:portobello_colony',
        'minecraft:brown_mushroom', 
        'minecraft:red_mushroom', 
        'collectorsreap:portobello', 
        'minecraft:crimson_fungus', 
        'minecraft:warped_fungus',
        'minecraft:kelp',
        'create:cinder_flour',
        'ratatouille:salty_dough', 
        'ratatouille:wheat_kernels', 
        'ratatouille:cocoa_solids', 
        'createdelight:corn_flour', 
        'bakeries:foamed_cream',
        'createdelight:board_noodles', 
        'createdelight:wafer_dough',
        'createdelight:vermicelli', 
        'bakeries:sweet_dough', 
        'bakeries:whole_wheat_dough', 
        'bakeries:bagel_dough', 
        'bakeries:whole_wheat_bagel_dough', 
        'bakeries:round_bread_dough', 
        'bakeries:berry_bread_dough', 
        'bakeries:brown_sugar_roll_dough', 
        'bakeries:pineapple_bun_dough', 
        'bakeries:meat_floss_bread_dough', 
        'bakeries:croissant_dough', 
        'bakeries:salt_croissant_dough', 
        'bakeries:mould_toast_dough', 
        'bakeries:mould_cheese_cocoa_toast_dough', 
        'bakeries:baguette_dough', 
        'bakeries:ciabatta_dough', 
        'bakeries:focaccia_dough', 
        'bakeries:country_bread_dough', 
        'ratatouille:cocoa_powder', 
        'ratatouille:cocoa_butter', 
        'ratatouille:dried_cocoa_beans', 
        'ratatouille:dried_cocoa_nibs',
        'ratatouille:salty_dough', 
        'ratatouille:wheat_kernels', 
        'ratatouille:cocoa_solids',
        'create_bic_bit:sweet_dough', 
        'create_bic_bit:crushed_nether_wart', 
        'casualness_delight:raw_gluten', 
        'casualness_delight:gluten', 
        'casualness_delight:raw_chicken_bobo_chicken', 
        'casualness_delight:raw_cabbage_bobo_chicken', 
        'casualness_delight:raw_potato_bobo_chicken', 
        'casualness_delight:potato_slice', 
        'createcafe:oreo_dough', 
        'createcafe:tapioca_flour', 
        'dungeonsdelight:gunk', 
        'dungeonsdelight:rotbulb', 
        'dungeonsdelight:sculk_polyp', 
        'dungeonsdelight:spider_extract', 
        'dungeonsdelight:rancid_reduction', 
        'dungeonsdelight:ghastly_spirits', 
        'dungeonsdelight:bloody_mary', 
        'dungeonsdelight:taro_milk_tea', 
        'dungeonsdelight:ancient_egg', 
        'dungeonsdelight:sculk_mayo_block', 
        'dungeonsdelight:spider_pie', 
        'dungeonsdelight:sculk_tart', 
        'dungeonsdelight:monster_cake', 
        'dungeonsdelight:glow_berry_gelatin_block', 
        'dungeonsdelight:ossobusco_block', 
        'dungeonsdelight:guardian_angel_block',
        'ends_delight:ender_pearl_grain', 
        'ends_delight:dried_chorus_flower', 
        'ends_delight:non_hatchable_dragon_egg', 
        'ends_delight:dragon_breath_soda', 
        'ends_delight:chorus_fruit_wine', 
        'festival_delicacies:uncooked_sweet_zongzi', 
        'festival_delicacies:uncooked_meat_zongzi', 
        'festival_delicacies:bamboo_leaf', 
        'festival_delicacies:mugwort', 
        'cavedelight:fiddlehead_tea', 
        'trailandtales_delight:cherry_petal', 
        'trailandtales_delight:dried_cherry_petal', 
        'trailandtales_delight:pitcher_plant', 
        'farmersrespite:rose_hips', 
        'neapolitan:banana_bunch', 
        'vintagedelight:oat',
        'crabbersdelight:clam', 
        'youkaishomecoming:soybean', 
        'youkaishomecoming:pods', 
        'youkaishomecoming:udumbara_flower', 
        'youkaishomecoming:mandrake_root', 
        'youkaishomecoming:matcha', 
        'youkaishomecoming:stripped_mandrake_root', 
        'youkaishomecoming:dried_mandrake_flower', 
        'collectorsreap:pomegranate', 
        'collectorsreap:lime_popsicle', 
        'collectorsreap:urchin',
        'brewinandchewin:unripe_scarlet_cheese_wheel',
    ])
})
