ServerEvents.tags("block", e => {
    e.add("quality_food:quality_blocks",
        "minecraft:grass",
        "minecraft:tall_grass",
        "minecraft:fern",
        "minecraft:large_fern"
    )
    Ingredient.of([
        "@vintagedelight",
        "@culturaldelights",
        "@fruitsdelight",
        "@collectorsreap",
        "@neapolitan",
        "@mynethersdelight",
        "@oceanic_delight",
        "@frycooks_delight",
        "@corn_delight",
        "@youkaishomecoming",
        "@nethervinery"
    ]).stacks.forEach(item => {
        if ((item.id.endsWith("_crate") || item.id.endsWith("_bag")) && item.block) {
            e.add("quality_food:quality_blocks", item.id)
        }
    })
    e.add("createdelight:quality_crops",
        "#minecraft:crops",
        "farmersrespite:tea_bush",
        "farmersrespite:small_tea_bush",
        "neapolitan:vanilla_vine",
        "neapolitan:strawberry_bush",
        "neapolitan:small_banana_frond",
        "neapolitan:banana_frond",
        "neapolitan:large_banana_frond",
        "neapolitan:mint",
        "minecraft:grass",
        "minecraft:tall_grass",
        "minecraft:fern",
        "minecraft:large_fern",
        "fruitsdelight:lemon_tree",
        "fruitsdelight:blueberry_bush",
        "fruitsdelight:cranberry_bush",
        "vinery:red_grape_bush",
        "vinery:white_grape_bush",
        "vinery:savanna_grape_bush_red",
        "vinery:savanna_grape_bush_white",
        "vinery:taiga_grape_bush_red",
        "vinery:taiga_grape_bush_white",
        "vinery:jungle_grape_bush_red",
        "vinery:jungle_grape_bush_white",
        "nethervinery:crimson_grape_bush",
        "nethervinery:warped_grape_bush",
        "collectorsreap:pomegranate_bush",
        "collectorsreap:lime_bush",
        'fruitsdelight:bayberry_leaves',
        'fruitsdelight:kiwi_leaves',
        'fruitsdelight:fig_leaves',
        'fruitsdelight:durian_leaves',
        'fruitsdelight:pear_leaves',
        'fruitsdelight:hawberry_leaves',
        'fruitsdelight:lychee_leaves',
        'fruitsdelight:mango_leaves',
        'fruitsdelight:persimmon_leaves',
        'fruitsdelight:peach_leaves',
        'fruitsdelight:orange_leaves', 
        'fruitsdelight:apple_leaves',
        'fruitsdelight:mangosteen_leaves'
    )
    e.add("quality_food:quality_blocks", 
        "#createdelight:quality_crops"
    )
})